# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy to Azure Web App - api-nest

on:
  push:
    branches:
      - main
    paths:
      - project/**/*
      - .github/workflows/azure-next-ssr-web-app.yml

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        working-directory: project

      - name: Upload artifact for packaging job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: |
            project/package*.json
            project/public
            project/.next

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install production dependencies
        run: |
          npm install --production
          ls -al

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'api-nest'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_ca9dbd88825742f28169399956958098 }}
          package: .
